version: '3'

services:
  front:
    image: httpd
    volumes: 
      - ./front/:/usr/local/apache2/htdocs
    ports:
      - 9000:80

  back:
    image: php:8.3-apache
    volumes:
      - ./back/:/var/www/html
    ports:
      - 3000:80